### ISSUE TITLE
set_priors with label 

### ISSUE THREAD

**Issue by juliosolisar** [macartan/gbiqq#120]
Setting priors with labels is currently not working

`make_model("X->Y") %>% set_priors(label="Y11", alphas = 3) %>% get_priors`
`make_model("X->Y") %>% set_priors(label="Y.11", alphas = 3) %>% get_priors`

throws "No change to priors"

**Comment by juliosolisar** [comment]
@macartan I see what you did here 

`make_priors_single(model, node = "X", label = "0", alphas = 9)`

but originally label should be working like this:
`make_priors_single(model, label = "X.0", alphas = 9)`

Options:

- Leave it as is
- Change it so it works as originally intended 
- Create new argument called param_name to do what I am trying to pass (will be very useful for Sisi's Shiny!)

Your call

**Comment by macartan** [comment]
Yes you should change to this:
> make_model("X->Y") %>% set_priors(label="11", alphas = 3) %>% get_priors
 X.0  X.1 Y.00 Y.10 Y.01 Y.11 
   1    1    1    1    1    3 

The param names have been shortened to remove redundacy. Note also that there is greater flexibility since you can condition on the node or not:

> make_model("X->M->Y") %>% set_priors(label="11", alphas = 3) %>% get_priors
 X.0  X.1 M.00 M.10 M.01 M.11 Y.00 Y.10 Y.01 Y.11 
   1    1    1    1    1    3    1    1    1    3 
> 
> make_model("X->M->Y") %>% set_priors(node = "Y", label="11", alphas = 3) %>% get_priors
 X.0  X.1 M.00 M.10 M.01 M.11 Y.00 Y.10 Y.01 Y.11 
   1    1    1    1    1    1    1    1    1    3

**Comment by juliosolisar** [comment]
Thanks!

**Comment by juliosolisar** [comment]
done
