### ISSUE TITLE
Restrictions should operate on nodal types

### ISSUE THREAD

**Issue by lilymedina** [macartan/gbiqq#86]
moving our discussion on restrictions from email here.

#### Current approach: restrictions operate on causal types
Currently, when we express a restriction using causal syntax, we first identify the causal types that are affected by the restriction using `reveal_outcomes` which goes in descendent order through all the endogenous variables in the model and reveals their outcomes according to the value of their ancestors.  Types whose outcomes satisfy the restriction are removed (or kept) from the model.

This approach allows us to restrict the effects that a variable can have on their descendants even when there's no arrow connecting them. As pointed by @ajacobs71 and @macartan, a restriction that operates on two nodes that are not directly connected suggests a confounding.

For instance, for a model `X -> M -> Y` we can restrict `Y[X=1] == 0`  ruling out a possible negative effect of X on Y, and implying that there's a (dotted) arrow modeling confounding between X and Y.  

`
`
#### Suggested approach: restrictions should operate strictly on nodal types
Instead, we need a function to set restrictions that operates at node levels, consider only the node's value and the value of its parents, and allow interventions on the node's parents only. This function should in one step identify nodal types satisfying a restriction.  

For a model  `M->Y<-X<-R`  the restriction below should be interpreted as remove all nodal types for which when M is 1, Y can be 0.

- `Y[M=1]==0  join_by = "|" `

The types below would be excluded from the model.

```
Y?0?1  
Y?1?0   
Y?0?0  
```

(Assuming position 2 and 4 represent M equals 1)

-  Restriction`Y[M=1]==0  join_by = "&" ` would exclude
 
```
Y?0?0
```

Note that this implies that Y could be 0 when `M = 1` for types `Y?1?0` and `Y?0?1`.

- Restriction `Y[R=0] == 1` wouldn't reduce the model.

**Comment by lilymedina** [comment]
On more technical details,  what do you think about using `lookup_type` syntax to write restriction statements? I'm think of something like:

```set_restrictions(model,  c(`Y | M=0 & X=1` = 1)) ```

or

`set_restrictions(model,  c("(Y | M=0 & X=0)   >  (Y | M=1 & X=1)" )) `

It should also be possible to restrict both conditions in the same call.

```set_restrictions(model,  c(``Y | M=0 & X=1` = 1), "(Y | M=0 & X=0)   >  (Y | M=1 & X=1)")) ```

**Comment by macartan** [comment]
Given need for wildcards causal type syntax might work best:

Say "A -> B -> C <- D"

Then expected behavior:

`set_restrictions(model, "C[B=1] > C[B=0]" )`
is interpreted as 
`set_restrictions(model, "C[B=1, D=.] > C[B=0, D=.]", join_by = "|" )`
and restricts any types where B affects C positively for *any* value of D

`set_restrictions(model, "C[B=1] > C[B=0]" , join_by = "&" )`
is interpreted as 
`set_restrictions(model, "C[B=1, D=.] > C[B=0, D=.]", join_by = "&" )`
and restricts all types where B affects C positively for *every* value of D

Other behavior:
`set_restrictions(model, "C[A=1] > C[A=0]")`
should yield message: "A is not a parent of C, no nodal types restricted"

Other behavior:
`set_restrictions(model, "C[B[A=1]=1] > C[B[A=1]=0]")`
should yield message: "Nested operations not allowed for nodal type restrictions, no nodal types restricted"

Other behavior: Restrictions on multiple nodes as ...
`set_restrictions(model, "C[B=1] > C[B=0]", "B[A=1]==1" )`
restricts nodal types for B and A
**However** in this case need to work out how join_by is assigned to different statements

Other behavior: Restrictions on level for roots
`set_restrictions(model, "A==1" )`

Other behavior: No restrictions on level for non roots
`set_restrictions(model, "B==1" )`
should yield message: "Restrictions on observational quantities not allowed. No nodal types restricted"

Perhaps allow
`set_restrictions(model, "C[]==1" )`
Interpreted as
`set_restrictions(model, "C[B=., D=.]==1" , join_by = "|")`

**Comment by lilymedina** [comment]
solved in https://github.com/macartan/gbiqq/pull/88
